version: '3.8'

services:
  backend:
    build: .
    container_name: smart-home-backend
    ports:
      - "8080:8080"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx256M -Xms256M -Dfile.encoding=UTF-8"
      
      # ── 1. CẤU HÌNH HIVEMQ CLOUD (MQTT BẢO MẬT SSL) ──
      MQTT_BROKER_URL: "ssl://c84e73f4fb39481295fc29855bdd5613.s1.eu.hivemq.cloud:8883"
      MQTT_USERNAME: "dangyb"
      MQTT_PASSWORD: "Asher@B@l@nc0urt"
      
      SPRING_DATASOURCE_URL: "jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres"
      SPRING_DATASOURCE_USERNAME: "postgres.fgoznfptwhbcliiuobvu"
      SPRING_DATASOURCE_PASSWORD: "Asher@B@l@nc0urt"
      
    deploy: 
      resources:
        limits:
          memory: 512M